apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-producer
  labels:
    app: simple-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-producer
  template:
    metadata:
      labels:
        app: simple-producer
    spec:
      containers:
      - name: simple-producer
        image: 576962245852.dkr.ecr.us-east-1.amazonaws.com/simple-producer:latest